services:
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: infrastructure-kafka
    hostname: kafka
    restart: on-failure
    ports:
      - "9092:9092"
      - "9094:9094"
      - "29092:29092"
    env_file:
      - .env.infrastructure

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: infrastructure-kafka-ui
    restart: on-failure
    ports:
      - "8888:8080"
    depends_on:
      - kafka
    env_file:
      - .env.infrastructure

  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    container_name: infrastructure-schema-registry
    restart: on-failure
    ports:
      - "8081:8081"
    env_file:
      - .env.infrastructure
    depends_on:
      - kafka
