schema:
  registry:
    url: ${SCHEMA_REGISTRY_URL:http://localhost:8081}
    subject: de.jwiegmann.registry.poc.control.dto.MyKafkaMessage

kafka:
  topic: ${KAFKA_TOPIC:my-topic}
  group: ${KAFKA_GROUP:test-group}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    urls:
      - name: AsyncAPI
        url: /async_api.yaml