schema:
  registry:
    url: http://schema-registry:8081
  subject: my-topic-value

kafka:
  topic: my-topic
  group: test-group

#logging:
#  level:
#    io.confluent.kafka.serializers: DEBUG
#    org.apache.kafka: DEBUG